name: coding_posts
recipe: drupal9
config:
  php: '7.4'
  composer_version: '1.10.1'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  drush: false
  xdebug: false
services:
  appserver:
    build:
      - composer install